using HarmonyLib;
using RimWorld;
using Verse;

namespace SK_Inspired_Unique.Patches
{
    // Unique weapons generate their own quality
    // and then the crafting process overrides the quality
    // We need to preserve the quality generated by the comp
    public static class CompQualityPatches
    {
        private static bool firstTime = false;
        [HarmonyPatch(typeof(CompQuality), "SetQuality")]
        public static class SetQuality
        {
            public static bool Prefix(CompQuality __instance)
            {
                if (!Toils_RecipePatches.FINISHING_PRODUCT_FLAG || __instance.parent.def != Toils_RecipePatches.uniqueWeaponDef)
                {
                    return true;
                }

                firstTime = !firstTime;

                if (firstTime)
                {
                    return true;
                }

                Toils_RecipePatches.uniqueWeapon = __instance.parent;
                return false;
            }
        }
    }
}
